import { Servicio } from './servicios';

// Minimal fallback dataset compatible with `Servicio` interface
export const serviciosFallback: Servicio[] = [
  {
    id: 1,
    titulo: "Salar de Uyuni Completo",
    descripcion: "Experiencia completa en el Salar de Uyuni",
    duracion: "3",
    categoria: { id: 1, nombre: "Aventura" },
    proveedor: { id: 0, rol: { id: 0, created_at: null, updated_at: null, nombre: "Proveedor" }, created_at: null, updated_at: null, nombre: "Proveedor", rubro: null, num_viajes: 0, telefono: null, fecha_nacimiento: null, genero: null, documento_identidad: null, pais: null, user: 0 },
    created_at: null,
    updated_at: null,
    capacidad_max: 10,
    punto_encuentro: "Uyuni",
    estado: "Activo",
    imagen_url: "/salar-de-uyuni-espejo.png",
    precio_usd: "1200",
    servicios_incluidos: ["Transporte 4x4", "Guía", "Alojamiento"],
  },
  {
    id: 2,
    titulo: "Lago Titicaca Sagrado",
    descripcion: "Descubre los misterios del Lago Titicaca",
    duracion: "2",
    categoria: { id: 2, nombre: "Cultural" },
    proveedor: { id: 0, rol: { id: 0, created_at: null, updated_at: null, nombre: "Proveedor" }, created_at: null, updated_at: null, nombre: "Proveedor", rubro: null, num_viajes: 0, telefono: null, fecha_nacimiento: null, genero: null, documento_identidad: null, pais: null, user: 0 },
    created_at: null,
    updated_at: null,
    capacidad_max: 8,
    punto_encuentro: "Puno",
    estado: "Activo",
    imagen_url: "/lago-titicaca.png",
    precio_usd: "800",
    servicios_incluidos: ["Transporte", "Guía", "Alojamiento"],
  },
  {
    id: 3,
    titulo: "Madidi Amazon Adventure",
    descripcion: "Aventura en el Parque Nacional Madidi",
    duracion: "4",
    categoria: { id: 3, nombre: "Naturaleza" },
    proveedor: { id: 0, rol: { id: 0, created_at: null, updated_at: null, nombre: "Proveedor" }, created_at: null, updated_at: null, nombre: "Proveedor", rubro: null, num_viajes: 0, telefono: null, fecha_nacimiento: null, genero: null, documento_identidad: null, pais: null, user: 0 },
    created_at: null,
    updated_at: null,
    capacidad_max: 12,
    punto_encuentro: "Rurrenabaque",
    estado: "Activo",
    imagen_url: "/madidi.png",
    precio_usd: "950",
    servicios_incluidos: ["Vuelo", "Lodge", "Comidas"],
  },
];